<a href="https://colab.research.google.com/github/SeanSDarcy2001/CISProgrammingAssignments/blob/main/CIS1HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computer Integrated Surgery: Programming Assignment 1

## PART 1
Develop (or develop proficiency with) a Cartesian math package for 3D points, rotations, and frame transformations.

In [1]:
## use package to represent 3D points
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

p1    = np.array([-1489., -4913.,  4345.])
p2    = np.array([ 2633., -3268.,  5249.])
pcalc = np.array([-3210., -4390.,  3930.])

def norm(v):
    return v / np.sqrt(np.dot(v, v))

In [2]:
## use packages to represent 3D rotations
def identity():
  return np.array([[1, 0,  0], [0, 1, 0], [0, 0, 1]])

# generate skew matrix from 1x3 array 
def skew(v) :
  skewArg = norm(v)
  ax = skewArg[0]
  ay = skewArg[1]
  az = skewArg[2]
  skew = np.array([[0, -az,  ay], [az, 0, -ax], [-ay, ax, 0]])
  return skew

# generate 3D Rotation matrix
# @Params: alpha, beta, gamma - Rotation angles about the x, y, and z axes respectively
# @Returns: 3D Rotation matrix
def RotfromAngles(alpha, beta, gamma) :
  Rx = np.array([[1, 0,  0], [0, np.cos(alpha), -np.sin(alpha)], [0, np.sin(alpha), np.cos(alpha)]])
  Ry = np.array([[np.cos(beta), 0,  np.sin(beta)], [0, 1, 0], [-np.sin(beta), 0, np.cos(beta)]])
  Rz = np.array([[np.cos(gamma), -np.sin(gamma),  0], [np.sin(gamma), np.cos(gamma), 0], [0, 0, 1]])
  R = RotfromComponents(Rx, Ry, Rz)
  return R

def smallAngleR(v, theta) :
  n = norm(v)
  return (identity() + skew(theta * n))

def RotfromComponents(Rx, Ry, Rz) :
  R = np.dot(np.dot(Rx, Ry), Rz)
  return R

# convert 3D vector into 4D homogeneous coords
def homogenousVector(v, scale) :
  Vx = scale * v[0]
  Vy = scale * v[1]
  Vz = scale * v[2]
  V = np.array([Vx, Vy, Vz, scale])

R = RotfromAngles(0, 1, 0)
print(R)

# theta = int
# RxTheta = np.array([1, 0,  0], [0, np.cos(theta), -np.sin(theta)], [0, np.sin(theta), np.cos(theta)]))
# RyTheta

[[ 0.54030231  0.          0.84147098]
 [ 0.          1.          0.        ]
 [-0.84147098  0.          0.54030231]]


In [3]:
## use packages to represent 3D frame transformations

class Frame:
  
  def __init__(self, R, p):
    self.R = R
    self.p = p
    self.F = self.getFrame()

  # define Frame using Rotation and Translation
  # @Params: Rotation R and Translation p
  # @Return: Frame
  def getFrame(self):
    F = np.row_stack((np.column_stack((self.R, self.p)),
                      [0,0,0,1]))
    return F

  # applies frame transformation to vector
  # @Params: Frame F and Vector v
  # @Return: transformed vector
  def appFrame(v):
    return np.dot(self.F, v)

  # applies inverse frame transformation to vector
  # @Params: Frame F and Vector v
  # @Return: transformed vector
  def appInvFrame(v):
    Finv = Frame(self.R.T, - (np.dot(self.R.T, self.p)))
    return np.dot(Finv.getFrame(), v)

# test case
p = np.array([5, 7, 9])
F = Frame(R, p)
print(F.getFrame())

[[ 0.54030231  0.          0.84147098  5.        ]
 [ 0.          1.          0.          7.        ]
 [-0.84147098  0.          0.54030231  9.        ]
 [ 0.          0.          0.          1.        ]]


In [4]:
# ## example?
# n1, n2, ncalc = [norm(p) for p in [p1, p2, pcalc]]

# new_zaxis  = norm(np.cross(n1, n2))
# new_xaxis  = n1
# zero       = np.zeros(3) 

# fig = plt.figure(figsize=[10, 8])
# ax  = fig.add_subplot(1, 1, 1, projection='3d')

# x, y, z = zip(zero, new_xaxis)
# plt.plot(x, y, z, '-k', linewidth=3)

# x, y, z = zip(zero, new_zaxis)
# plt.plot(x, y, z, '--k', linewidth=3)

# x, y, z = zip(zero, n2)
# plt.plot(x, y, z, '-r', linewidth=1)

# x, y, z = zip(zero, ncalc)
# plt.plot(x, y, z, '--g', linewidth=1)

# ax.set_xlim(-1, 1)
# ax.set_ylim(-1, 1)
# ax.set_zlim(-1, 1)

# plt.show()

## PART 2

Develop a 3D point set to 3D point set registration algorithm

K. Arun, et. al., IEEE PAMI, Vol 9, no 5, pp 698-700, Sept 1987 

In [5]:
#Writing points with rows as the coordinates
p1_t = np.array([[0,0,0],[1,0,0],[0,1,0]])
p2_t = np.array([[0,0,1], [1,0,1],[0,0,2]]) #Approx transformation is 90 degree rot over x-axis and +1 in Z axis

#Take transpose as columns should be the points
p1 = p1_t.transpose()
p2 = p2_t.transpose()

#Calculate centroids
p1_c = np.mean(p1, axis = 1).reshape((-1,1)) #If you don't put reshape then the outcome is 1D with no rows/colums and is interpeted as rowvector in next minus operation, while it should be a column vector
p2_c = np.mean(p2, axis = 1).reshape((-1,1))

#Subtract centroids
q1 = p1-p1_c
q2 = p2-p2_c

q1 = norm(p1)

print(q1)
print(q2)

#Calculate covariance matrix
H=np.matmul(q1,q2.T)

#Calculate singular value decomposition (SVD)
U, X, V_t = np.linalg.svd(H) #the SVD of linalg gives you Vt

#Calculate rotation matrix
R = np.dot(V_t.T,U.T)

assert np.allclose(np.linalg.det(R), 1.0), "Rotation matrix of N-point registration not 1, see paper Arun et al."

#Calculate translation matrix
T = p2_c - np.matmul(R,p1_c)

#Check result
result = T + np.matmul(R,p1)
if np.allclose(result,p2):
    print("transformation is correct!")
else:
    print("transformation is wrong...")

[[nan inf  0.]
 [nan nan inf]
 [nan nan nan]]
[[-0.33333333  0.66666667 -0.33333333]
 [ 0.          0.          0.        ]
 [-0.33333333 -0.33333333  0.66666667]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


LinAlgError: ignored

# Contributions

## Seby


*   developed proficiency with a Cartesian math package for 3D points rotations, and frame transformations. (1)


## Alex


*   developed proficiency with a Cartesian math package for 3D points rotations, and frame transformations. (1)
*   created Frame object with transformation functionality. (1)

